### ISSUE TITLE
Get-MasterZoneFile throws HTTP 406 Not Acceptable error

### ISSUE THREAD

**Issue by rmbolger** [akamai-contrib/akamaipowershell#2]
Attempting to use `Get-MasterZoneFile` currently throws a WebException error due to an HTTP 406 Not Acceptable response by the server. Depending on the PowerShell version, it may also include the JSON response body that gives a better indication of what's wrong.

```
{
    "type":  "https://problems.luna.akamaiapis.net/authoritative-dns/notAcceptable",
    "title":  "Unable to\r\nrespect Accept header",
    "instance":  "1539501e-fce1-4998-8dc1-2e1a03fcd02a",
    "status":  406,
    "detail":  "The content type you\r\nrequested cannot be produced.",
    "supportedContentTypes":  [
                                  "application/json"
                              ],
    "requestedContentType":  "text/dns"
}
```

Apparently not all endpoints support sending `application/json` responses. So `Invoke-AkamaiRestMethod` needs to be modified to support a configurable Accept header.

**Comment by stuartio** [comment]
Apologies for the delay, didnt have my notifications set up, and wasnt actually aware anyone else was using this yet. :-) Comments in the PR

**Comment by stuartio** [comment]
Accept header can be passed by using AdditionalHeaders param. Any members there will overwrite headers in Invoke-AkamaiRestMethod
