### ISSUE TITLE
Getting 401 when trying to upload a third-party certificate

### ISSUE THREAD

**Issue by brantpeery** [akamai-contrib/akamaipowershell#29]
When I try to use the Invoke-AkamaiRestMethod to upload a certificate and it's chain, I get 

Invoke-RestMethod : {
  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/deny",
  "title": "Not authorized",
  "status": 401,
  "detail": "The signature does not match",
....
}

Does this mean that the Invoke-AkamaiRestMethod is creating the signature incorrectly for this large payload? All other calls to the api seem to work fine.

**Comment by stuartio** [comment]
Seems likely. Can you send me which function you are using so I can reproduce? Issues like this occasionally come up and I need to tweak the signature generation to match, but it shouldnt be a problem

**Comment by brantpeery** [comment]
The code that I have written to upload a cert is like this:

```powershell
$url = "$EnrolmentChangeLocation/input/update/third-party-csr" #third-party-cert-and-trust-chain"
    $additionalHeaders = @{
        "Content-Type" = "application/vnd.akamai.cps.certificate-and-trust-chain.v1+json"
        "Accept" = "application/vnd.akamai.cps.change-id.v1+json"
    }
    $body = @{
        certificate = $CertificatePEM
        trustChain = $CertificateChainPEM
    }
    try {
        $Result = Invoke-AkamaiRestMethod -Method POST -Path $url -Body $body -AdditionalHeaders $additionalHeaders
        return $Result
    }
         catch {
        throw $_.Exception
    }
```
This has the length of: the certificate and two cert chain certificates. So pretty long.

**Comment by brantpeery** [comment]
So I did find the problem. I was sending the body as an object, when the Invoke-AkamaiRestMethod assumes it is a string (json for most things). Because of that it was not calculating the signature right as it was using the object. However, the native Invoke-RestMethod does jsonify the object so the call from akamai api perspective has the write body, but the wrong hash in the signature. 
To fix this, the Invoke-AkamaiRestMethod should either declare the parameter as a string, or convert the $body to json before calculating the hash.

**Comment by stuartio** [comment]
So the $Body variable used to have the [string] type specified, but that actually broke signing for something else. Iirc there are occasions where the body is not a string and casting it to a file caused issues. I will dive back into the code and see if I can find them. For your use case it might be better to convert the object to a string in the calling function, rather than in the shared one.
